# Generated by Django 2.0.2 on 2018-02-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
